In [1]:
import json

In [2]:
import numpy as np
import pandas as pd


In [3]:
import matplotlib.pyplot as plt

In [4]:
import cv2

In [5]:
filename_labels='C:\Users\Sean Violante\Documents\Projects\kaggle\kaggle-drc-viewer\\filenames.json'
filename_desc='C:\Users\Sean Violante\Documents\Projects\\kaggle\\train\\images.txt'

In [6]:
filename_desc

'C:\\Users\\Sean Violante\\Documents\\Projects\\kaggle\\train\\images.txt'

In [7]:
a=open(filename_labels)
z=a.readline()
g=json.loads(z)

In [8]:
df

NameError: name 'df' is not defined

In [9]:
dfs=[]
for k,images in g.iteritems():
    dfs.append(pd.DataFrame({'image':images,'label':k}))
df_all=pd.concat(dfs)

In [10]:
df_all.label=df_all.label.astype(np.int)

In [11]:
df_all.head()

image  label
0   train/15_left.jpeg      1
1  train/17_right.jpeg      1
2   train/30_left.jpeg      1
3   train/36_left.jpeg      1
4  train/114_left.jpeg      1

In [12]:
%matplotlib

Using matplotlib backend: Qt4Agg


In [13]:
df_all.label.hist()

In [33]:
df_all.label.describe()

count    35126.000000
mean         0.526049
std          0.970390
min          0.000000
25%          0.000000
50%          0.000000
75%          1.000000
max          4.000000
Name: label, dtype: float64

In [14]:
df_all.label.value_counts()

0    25810
2     5292
1     2443
3      873
4      708
dtype: int64

In [15]:
image_desc=pd.read_csv(filename_desc,sep=' ',header=None,names=['filename','type','dim','dimx','bit','col','mem','x','y'])

In [16]:
image_desc.head()

filename  type        dim           dimx    bit   col      mem  \
0      10003_left.jpeg  JPEG  4752x3168  4752x3168+0+0  8-bit  sRGB  1.563MB   
1  10003_right.jpeg[1]  JPEG  4752x3168  4752x3168+0+0  8-bit  sRGB  1.584MB   
2   10007_left.jpeg[2]  JPEG  3456x2304  3456x2304+0+0  8-bit  sRGB    823KB   
3  10007_right.jpeg[3]  JPEG  3456x2304  3456x2304+0+0  8-bit  sRGB    863KB   
4   10009_left.jpeg[4]  JPEG  3888x2592  3888x2592+0+0  8-bit  sRGB  1.542MB   

        x         y  
0  0.000u  0:00.000  
1  0.000u  0:00.001  
2  0.000u  0:00.000  
3  0.000u  0:00.000  
4  0.000u  0:00.000

In [17]:
image_desc[['dim_x','dim_y']]=image_desc.dim.str.split('x').apply(pd.Series)

In [18]:
image_desc.tail()

filename  type        dim           dimx    bit   col  \
35121  9998_right.jpeg[35121]  JPEG  4272x2848  4272x2848+0+0  8-bit  sRGB   
35122   9999_left.jpeg[35122]  JPEG  3888x2592  3888x2592+0+0  8-bit  sRGB   
35123  9999_right.jpeg[35123]  JPEG  3888x2592  3888x2592+0+0  8-bit  sRGB   
35124     99_left.jpeg[35124]  JPEG  2560x1920  2560x1920+0+0  8-bit  sRGB   
35125    99_right.jpeg[35125]  JPEG  2560x1920  2560x1920+0+0  8-bit  sRGB   

           mem       x         y dim_x dim_y  
35121  1.583MB  0.000u  0:00.000  4272  2848  
35122  1.409MB  0.000u  0:00.001  3888  2592  
35123  1.457MB  0.016u  0:00.000  3888  2592  
35124    333KB  0.000u  0:00.001  2560  1920  
35125    380KB  0.000u  0:00.000  2560  1920

In [19]:
image_desc['name']=image_desc.filename.str.split('.').str[0] # get up to .

In [20]:
df_all['name']=df_all['image'].str[6:-5]

In [21]:
image_table=image_desc.merge(df_all,on='name')

In [22]:
image_table.groupby('label').apply(lambda x: x.head())

filename  type        dim           dimx    bit   col  \
label                                                                           
0     0          10003_left.jpeg  JPEG  4752x3168  4752x3168+0+0  8-bit  sRGB   
      1      10003_right.jpeg[1]  JPEG  4752x3168  4752x3168+0+0  8-bit  sRGB   
      2       10007_left.jpeg[2]  JPEG  3456x2304  3456x2304+0+0  8-bit  sRGB   
      3      10007_right.jpeg[3]  JPEG  3456x2304  3456x2304+0+0  8-bit  sRGB   
      4       10009_left.jpeg[4]  JPEG  3888x2592  3888x2592+0+0  8-bit  sRGB   
1     26     10030_left.jpeg[26]  JPEG  2592x1944  2592x1944+0+0  8-bit  sRGB   
      27    10030_right.jpeg[27]  JPEG  2592x1944  2592x1944+0+0  8-bit  sRGB   
      64     10085_left.jpeg[64]  JPEG  3888x2592  3888x2592+0+0  8-bit  sRGB   
      65    10085_right.jpeg[65]  JPEG  3888x2592  3888x2592+0+0  8-bit  sRGB   
      123  10150_right.jpeg[123]  JPEG  4928x3264  4928x3264+0+0  8-bit  sRGB   
2     25     1002_right.jpeg[25]  JPEG  3888x2592  3888x2592+0+0  8-bit  sRGB   
      36     10043_left.jpeg[36]  JPEG  2592x1944  2592x1944+0+0  8-bit  sRGB   
      37    10043_right.jpeg[37]  JPEG  2592x1944  2592x1944+0+0  8-bit  sRGB   
      82     10109_left.jpeg[82]  JPEG  3888x2592  3888x2592+0+0  8-bit  sRGB   
      83    10109_right.jpeg[83]  JPEG  3888x2592  3888x2592+0+0  8-bit  sRGB   
3     24      1002_left.jpeg[24]  JPEG  3888x2592  3888x2592+0+0  8-bit  sRGB   
      40     10047_left.jpeg[40]  JPEG  3888x2592  3888x2592+0+0  8-bit  sRGB   
      66      1008_left.jpeg[66]  JPEG  3888x2592  3888x2592+0+0  8-bit  sRGB   
      67     1008_right.jpeg[67]  JPEG  3888x2592  3888x2592+0+0  8-bit  sRGB   
      96     10125_left.jpeg[96]  JPEG  4272x2848  4272x2848+0+0  8-bit  sRGB   
4     16     10017_left.jpeg[16]  JPEG  3888x2592  3888x2592+0+0  8-bit  sRGB   
      17    10017_right.jpeg[17]  JPEG  3888x2592  3888x2592+0+0  8-bit  sRGB   
      41    10047_right.jpeg[41]  JPEG  3888x2592  3888x2592+0+0  8-bit  sRGB   
      169  10193_right.jpeg[169]  JPEG  3888x2592  3888x2592+0+0  8-bit  sRGB   
      280   10312_left.jpeg[280]  JPEG  4928x3264  4928x3264+0+0  8-bit  sRGB   

               mem       x         y dim_x dim_y         name  \
label                                                           
0     0    1.563MB  0.000u  0:00.000  4752  3168   10003_left   
      1    1.584MB  0.000u  0:00.001  4752  3168  10003_right   
      2      823KB  0.000u  0:00.000  3456  2304   10007_left   
      3      863KB  0.000u  0:00.000  3456  2304  10007_right   
      4    1.542MB  0.000u  0:00.000  3888  2592   10009_left   
1     26     783KB  0.000u  0:00.001  2592  1944   10030_left   
      27     787KB  0.000u  0:00.000  2592  1944  10030_right   
      64   1.646MB  0.000u  0:00.000  3888  2592   10085_left   
      65   1.538MB  0.000u  0:00.000  3888  2592  10085_right   
      123  1.358MB  0.000u  0:00.000  4928  3264  10150_right   
2     25   1.406MB  0.000u  0:00.000  3888  2592   1002_right   
      36     686KB  0.000u  0:00.000  2592  1944   10043_left   
      37     702KB  0.000u  0:00.000  2592  1944  10043_right   
      82   1.043MB  0.000u  0:00.000  3888  2592   10109_left   
      83   1.076MB  0.000u  0:00.000  3888  2592  10109_right   
3     24    1.45MB  0.000u  0:00.000  3888  2592    1002_left   
      40   1.382MB  0.000u  0:00.000  3888  2592   10047_left   
      66   1.159MB  0.000u  0:00.000  3888  2592    1008_left   
      67   1.164MB  0.000u  0:00.000  3888  2592   1008_right   
      96   1.644MB  0.000u  0:00.000  4272  2848   10125_left   
4     16   1.212MB  0.000u  0:00.000  3888  2592   10017_left   
      17   1.209MB  0.000u  0:00.000  3888  2592  10017_right   
      41   1.378MB  0.000u  0:00.000  3888  2592  10047_right   
      169  1.566MB  0.000u  0:00.000  3888  2592  10193_right   
      280  1.056MB  0.000u  0:00.000  4928  3264   10312_left   

                            image  label  
label                                

In [26]:
image_desc.dim_x=image_desc.dim_x.astype(np.int)

In [27]:
image_desc.dim_y=image_desc.dim_y.astype(np.int)

In [62]:
image_desc.dim_y.hist()

In [59]:
import matplotlib.pyplot as plt

In [61]:
plt.show()

In [75]:
df_all.head()

image  label      name  number     lr
0   train/15_left.jpeg      1   15_left      15   left
1  train/17_right.jpeg      1  17_right      17  right
2   train/30_left.jpeg      1   30_left      30   left
3   train/36_left.jpeg      1   36_left      36   left
4  train/114_left.jpeg      1  114_left     114   left

In [64]:
df_all[df_all.image=='train/10003_left.jpeg']

image  label
5802  train/10003_left.jpeg      0

In [95]:
df_all.head(100000)[df_all.head(100000).label==4]

image  label         name  number     lr
0        train/16_left.jpeg      4      16_left      16   left
1       train/16_right.jpeg      4     16_right      16  right
2       train/217_left.jpeg      4     217_left     217   left
3      train/217_right.jpeg      4    217_right     217  right
4       train/294_left.jpeg      4     294_left     294   left
5      train/294_right.jpeg      4    294_right     294  right
6       train/326_left.jpeg      4     326_left     326   left
7      train/326_right.jpeg      4    326_right     326  right
8       train/367_left.jpeg      4     367_left     367   left
9      train/367_right.jpeg      4    367_right     367  right
10      train/405_left.jpeg      4     405_left     405   left
11     train/405_right.jpeg      4    405_right     405  right
12      train/406_left.jpeg      4     406_left     406   left
13     train/406_right.jpeg      4    406_right     406  right
14     train/439_right.jpeg      4    439_right     439  right
15     train/458_right.jpeg      4    458_right     458  right
16      train/670_left.jpeg      4     670_left     670   left
17     train/670_right.jpeg      4    670_right     670  right
18      train/936_left.jpeg      4     936_left     936   left
19     train/936_right.jpeg      4    936_right     936  right
20      train/986_left.jpeg      4     986_left     986   left
21     train/1084_left.jpeg      4    1084_left    1084   left
22    train/1084_right.jpeg      4   1084_right    1084  right
23    train/1099_right.jpeg      4   1099_right    1099  right
24     train/1138_left.jpeg      4    1138_left    1138   left
25    train/1138_right.jpeg      4   1138_right    1138  right
26     train/1350_left.jpeg      4    1350_left    1350   left
27     train/1430_left.jpeg      4    1430_left    1430   left
28    train/1430_right.jpeg      4   1430_right    1430  right
29     train/1663_left.jpeg      4    1663_left    1663   left
..                      ...    ...          ...     ...    ...
678  train/41761_right.jpeg      4  41761_right   41761  right
679  train/41852_right.jpeg      4  41852_right   41852  right
680  train/42022_right.jpeg      4  42022_right   42022  right
681   train/42316_left.jpeg      4   42316_left   42316   left
682   train/42358_left.jpeg      4   42358_left   42358   left
683  train/42442_right.jpeg      4  42442_right   42442  right
684   train/42484_left.jpeg      4   42484_left   42484   left
685  train/42484_right.jpeg      4  42484_right   42484  right
686   train/42815_left.jpeg      4   42815_left   42815   left
687  train/42815_right.jpeg      4  42815_right   42815  right
688   train/43008_left.jpeg      4   43008_left   43008   left
689   train/43050_left.jpeg      4   43050_left   43050   left
690  train/43050_right.jpeg      4  43050_right   43050  right
691   train/43141_left.jpeg      4   43141_left   43141   left
692  train/43141_right.jpeg      4  43141_right   43141  right
693   train/43199_left.jpeg      4   43199_left   43199   left
694  train/43199_right.jpeg      4  43199_right   43199  right
695   train/43339_left.jpeg      4   43339_left   43339   left
696  train/43339_right.jpeg      4  43339_right   43339  right
697   train/43379_left.jpeg      4   43379_left   43379   left
698  train/43379_right.jpeg      4  43379_right   43379  right
699  train/43839_right.jpeg      4  43839_right   43839  right
700   train/43997_left.jpeg      4   43997_left   43997   left
701  train/43997_right.jpeg      4  43997_right   43997  right
702   train/43998_left.jpeg      4   43998_left   43998   left
703   train/44100_left.jpeg      4   44100_left   44100   left
704   train/44247_left.jpeg      4   44247_left   44247   left
705  train/44247_right.jpeg      4  44247_right   44247  right
706   train/44249_left.jpeg      4   44249_left   44249   left
707  train/44249_right.jpeg      4  44249_right   44249  right

[708 rows x 5 columns]

In [28]:
df_all[['number','lr']]=df_all.name.str.split('_').apply(pd.Series)

In [29]:
df_all.number=df_all.number.astype(np.int)

In [106]:
df_all.head(100000)[df_all.head(100000).label==4].loc[:24,'image'].to_clipboard()

In [102]:
df_all.head(100000)[df_all.head(100000).label==0].loc[:24,'image'].to_clipboard()

In [25]:
files_dir="C:\\Users\\Sean Violante\\Documents\\Projects\\kaggle\\processed\\run-normal_01\\train"

In [23]:
w=cv2.namedWindow("retina")

In [36]:
w1=cv2.namedWindow("retina_edge")

In [72]:
w2=cv2.namedWindow("retina_blur")

In [25]:
np.array(a1.shape[0:2])+2

array([258, 258], dtype=int64)

In [26]:
mas=np.zeros(np.array(a1.shape[0:2])+2,np.uint8)

In [189]:
l0_samp=df_all.loc[df_all.label==0,'name'].head(100)

In [190]:
l4_samp=df_all.loc[df_all.label==4,'name'].head(100)

In [28]:
a1=cv2.imread(files_dir+"\\"+"10030_left.png")

In [31]:
a1_g=a1[:,:,1].squeeze()

In [33]:
cv2.imshow("retina",a1_g)
#cv2.waitKey(0)

In [73]:
blur = cv2.GaussianBlur(a1_g,(11,11),0)
cv2.imshow("retina_blur",blur)


In [108]:
laplacian = cv2.Laplacian(a1_g,cv2.CV_64F,ksize=31)


In [104]:
np.histogram(laplacian.ravel(),bins=100)

(array([    1,     0,     1,     2,     3,     1,     0,     1,     2,
            3,     2,     3,     1,     5,     5,     6,     2,     5,
            9,    23,    34,    40,    71,    84,    81,    68,    84,
          105,    75,    61,    89,    84,   118,   125,   140,   165,
          156,   206,   195,   289,   369,   475,   634,   843,  1185,
         1794,  2681,  4389,  7169, 21847,  7962,  4002,  2131,  1303,
          935,   781,   635,   536,   483,   351,   295,   250,   221,
          224,   247,   203,   144,   118,    96,   100,    97,   112,
          140,   112,   100,    66,    36,    17,    15,    13,    12,
            3,     7,     4,     2,     5,     3,     1,     4,     7,
            2,     5,     2,     8,     3,     3,     2,     3,     1,     3]),
 array([-2492.  , -2441.76, -2391.52, -2341.28, -2291.04, -2240.8 ,
        -2190.56, -2140.32, -2090.08, -2039.84, -1989.6 , -1939.36,
        -1889.12, -1838.88, -1788.64, -1738.4 , -1688.16, -1637.92,
      

In [109]:
cv2.imshow("retina_edge",(laplacian>100)*np.ubyte(128))

In [ ]:
# canny 25, 75

In [ ]:
a=cv2.getDerivKernels

In [82]:
(laplacian.ravel()).shape

(65536L,)

In [105]:
plt.figure(1)
plt.clf()
plt.hist(laplacian.ravel(),bins=100)


(array([  1.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          2.00000000e+00,   3.00000000e+00,   1.00000000e+00,
          0.00000000e+00,   1.00000000e+00,   2.00000000e+00,
          3.00000000e+00,   2.00000000e+00,   3.00000000e+00,
          1.00000000e+00,   5.00000000e+00,   5.00000000e+00,
          6.00000000e+00,   2.00000000e+00,   5.00000000e+00,
          9.00000000e+00,   2.30000000e+01,   3.40000000e+01,
          4.00000000e+01,   7.10000000e+01,   8.40000000e+01,
          8.10000000e+01,   6.80000000e+01,   8.40000000e+01,
          1.05000000e+02,   7.50000000e+01,   6.10000000e+01,
          8.90000000e+01,   8.40000000e+01,   1.18000000e+02,
          1.25000000e+02,   1.40000000e+02,   1.65000000e+02,
          1.56000000e+02,   2.06000000e+02,   1.95000000e+02,
          2.89000000e+02,   3.69000000e+02,   4.75000000e+02,
          6.34000000e+02,   8.43000000e+02,   1.18500000e+03,
          1.79400000e+03,   2.68100000e+03,   4.38900000e+03,
        

In [142]:
l4_samp

0       16_left
1      16_right
2      217_left
3     217_right
4      294_left
5     294_right
6      326_left
7     326_right
8      367_left
9     367_right
10     405_left
11    405_right
12     406_left
13    406_right
14    439_right
...
85    5304_right
86     5825_left
87    5825_right
88     5838_left
89     6017_left
90    6017_right
91     6096_left
92    6096_right
93     6613_left
94    6613_right
95     6707_left
96    6707_right
97     6719_left
98    6719_right
99    6997_right
Name: name, Length: 100, dtype: object

In [195]:
def read_images(image_names):
    images=[]
    masks=[]
    
    hists=np.zeros((len(image_names),128,128,128)) # sparse?
    for i,im in enumerate(image_names):
        a1=cv2.imread(files_dir+"\\"+im+".png")
        images.append(a1)
        mas=np.zeros(np.array(a1.shape[0:2])+2,np.uint8)
        z=cv2.floodFill(a1, mas, (0,0),0,  flags=cv2.FLOODFILL_MASK_ONLY|1<<8|4)
        z=cv2.floodFill(a1, mas, (0,255),0,  flags=cv2.FLOODFILL_MASK_ONLY|1<<8|4)
        z=cv2.floodFill(a1, mas, (255,0),0,  flags=cv2.FLOODFILL_MASK_ONLY|1<<8|4)
        z=cv2.floodFill(a1, mas, (255,255),0,  flags=cv2.FLOODFILL_MASK_ONLY|1<<8|4)
        mas1=np.logical_not(mas[1:257,1:257])*np.uint8(1)
        masks.append(mas1)
        a2 = cv2.cvtColor(a1,cv2.COLOR_BGR2YCrCb)
        hist=cv2.calcHist([a2], [0,1,2], mas1, [128]*3,[0,256]*3)
        hists[i,:,:,:]=hist
    return images,masks,hists

In [191]:
images_l4=images
masks_l4=masks

In [214]:
def pca_images(images,masks,cvt=None):
    mns=np.zeros((len(images),3))
    eig_vecs=np.zeros((len(images),3,3))
    eig_vals=np.zeros((len(images),3))
    for i,im in enumerate(images):
        im_cvt= cv2.cvtColor(im,cvt)
        #dat=im_cvt.reshape((-1,3))
        dat1=im_cvt[ masks[i].astype(bool),:]
        mns[i,:] = dat1.mean(axis=0)
        u, s, v = np.linalg.svd(dat1 - mns[i,:],full_matrices=False)
        eig_vecs[i,:]=v
        eig_vals[i,:]=s
    return mns,eig_vecs,eig_vals

In [196]:
images_l0,masks_l0,hists_l0=read_images(l0_samp)

In [ ]:
# make hists_l4 a numpy  array

In [215]:
mns_l0,eig_vecs_l0,eig_vals_l0=pca_images(images_l0,masks_l0,cvt=cv2.COLOR_BGR2YCrCb)

In [216]:
mns_l0[1:10,:]

array([[  52.00975198,  131.31240882,  124.43933809],
       [  89.04489521,  161.99377043,  100.05295136],
       [  89.9298367 ,  162.16595581,   99.48487992],
       [  89.33085969,  156.32518933,  102.83858507],
       [  57.64518709,  135.34536799,  122.81424355],
       [  78.81892799,  138.91697905,  118.85037398],
       [ 101.31904598,  149.50086048,  111.60871414],
       [ 103.86107959,  149.9102164 ,  110.42972929],
       [ 108.68984446,  136.94422842,  117.8136627 ]])

In [219]:
a1=images[0]
a2= cv2.cvtColor(a1,cv2.COLOR_BGR2YCrCb)
a2.reshape((-1,3)).mean(axis=0)

array([  95.39428711,  140.09594727,  118.2167511 ])

In [211]:
%debug

> c:\anaconda\lib\site-packages\numpy\linalg\linalg.py(1328)svd()
   1327         u, s, vt = gufunc(a, signature=signature, extobj=extobj)
-> 1328         u = u.astype(result_t)
   1329         s = s.astype(_realType(result_t))

ipdb> q


In [259]:
plt.figure(8)
plt.clf()
for i in range(8):
    im_cvt= cv2.cvtColor(images_l4[i][:,:,:],cv2.COLOR_BGR2YCrCb)
    for j in range(3):
        plt.subplot(8,3,i*3+j+1)
        plt.imshow(im_cvt[:,:,j])
    

In [263]:
z1=images_l4[i]-mns_l0[i,:]
z2=np.tensordot(z1,eig_vecs_l0[i,:,:],1)
z2.shape

(256L, 256L, 3L)

In [ ]:
plt.figure(8)
plt.clf()
for i in range(8):
    images_l4[i][:,:,:]
    for j in range(3):
        plt.subplot(8,3,i*3+j+1)
        plt.imshow(im_cvt[:,:,j])
    

In [252]:
eig_vals_l0[0,0]/np.sqrt(256*256)
    

37.976685977844369

In [ ]:
plt.figure(7)
plt.clf()
for i in range(24):
    plt.subplot(6,4,i+1)
    
    plt.imshow(np.log(hists_l0[i,:,:,:].sum(axis=0)+1).T,origin='bottom',extent=(0,256,0,256))
    plt.plot(mns_l0[i,1],mns_l0[i,2],'go')
    plt.plot(mns_l0[i,1] + eig_vals_l0[i,0]/np.sqrt(masks[i].sum())*np.array([[0],[eig_vecs_l0[i,0,1]]]), \
             mns_l0[i,2] + eig_vals_l0[i,0]/np.sqrt(masks[i].sum())*np.array([[0],[eig_vecs_l0[i,0,2]]]),'g-')
    
    plt.title(' {} {} {}'.format(i,int(mns_l0[i,1]),int(mns_l0[i,2])))

In [275]:
plt.figure(4)
plt.clf()
plt.imshow(masks_l0[0])
print masks_l0[0][128,128]

1


In [280]:
plt.figure(5)
a1=cv2.cvtColor(images_l0[0][:,:,:],cv2.COLOR_BGR2RGB)
gray= a1[:,:,1]

sift = cv2
kp = sift.detect(gray,None)

img=cv2.drawKeypoints(gray,kp)
plt.imshow(img)

AttributeError: 'module' object has no attribute 'sift'

In [162]:
plt.imshow(i_rgb+np.logical_not(masks[0])[:,:,np.newaxis]*(128,128,128))

In [177]:
plt.figure(5)
plt.imshow(i_rgb+np.logical_not(masks[0])[:,:,np.newaxis]*(128,128,128))

In [178]:
plt.figure(4)
plt.imshow(i_rgb)

In [88]:
mas1.shape

(256L, 256L)

In [99]:
[[0,256]]*3

[[0, 256], [0, 256], [0, 256]]

In [ ]:
df_all.head(100000)[df_all.head(100000).label==4].loc[:24,'image'].to_clipboard()

In [131]:
hists=cv2.calcHist([a2], [0,1,2], np.logical_not(mas1)*np.uint8(255), [128]*3,[0,256]*3)

In [143]:
hists.shape

(128L, 128L, 128L)

In [149]:
f=plt.figure(3)
f.clf()
i=f.gca().imshow(np.log(hists.sum(axis=(0))+1))
f.colorbar(i)


<matplotlib.colorbar.Colorbar instance at 0x0000000010751988>

In [30]:
plt.imshow(mas)

In [290]:
def plot_sift_descriptors(descs,ax=None):
    if ax is None:
        ax = plt.gca()
    for desc in descs:
        c=plt.Circle((desc['x'], desc['y']),desc['s'])
        ax.add_artist(c)
        
        

In [281]:
z1='C:\\Users\\Sean Violante\\Documents\\Projects\\vlfeat\\vlfeat\\x64\\Debug\\box.pgm'
a1=plt.imread(z1)
plt.figure(9)
plt.clf()
plt.imshow(a1)

In [283]:
z=plt.imshow(a1)
z.set_cmap('gray')

In [299]:
plt.figure(11)
plot_sift_descriptors([{'x':133.92, 'y':135.88, 's':1.38}],plt.gca())

In [300]:
plot_sift_descriptors([{'x':133.92, 'y':135.88, 's':14.38}],z.axes)

In [295]:
plt.show()

In [297]:
plt.plot(133,135,'rx')

In [43]:
circs=cv2.HoughCircles(mas,method=cv2.HOUGH_GRADIENT,dp=2,minDist=10,param1=1,param2=1,minRadius=75,maxRadius=150)

In [86]:
circs[0,0:10]

array([[ 117.        ,  121.        ,  115.24755859],
       [ 107.        ,  125.        ,  110.22250366],
       [ 135.        ,  129.        ,  134.62911987],
       [ 117.        ,  133.        ,  117.9872818 ],
       [ 125.        ,  127.        ,  125.17188263],
       [ 135.        ,  139.        ,  118.80236053],
       [ 143.        ,  121.        ,  113.03981781],
       [ 123.        ,  143.        ,  123.35720825],
       [ 133.        ,  109.        ,  126.57013702],
       [ 147.        ,  131.        ,  111.19802094]], dtype=float32)

In [76]:
circle1=plt.Circle(tuple(circs[0,0,0:2]),circs[0,0,2],color='k')

In [39]:
edges=cv2.Canny(mas,threshold1=.1,threshold2=1)

In [75]:
plt.imshow(edges)

In [73]:
f1=plt.figure(1)

In [77]:
f1.gca().add_artist(circle1)

In [74]:
f1.clf()

In [56]:
circs.shape

(1L, 178L, 3L)

In [59]:
z=plt.figure(2)
z.gca().add_artist(circle1)

In [60]:
plt.show()

In [65]:
z.canvas.draw()

In [66]:
z.show()

In [68]:
z.gca().artists

In [69]:
circs[0,0,0:2]

array([ 117.,  121.], dtype=float32)

In [78]:
f1.canvas.draw()

In [84]:
plt.figure(figsize=(8,8))
ax=plt.subplot(aspect='equal')

#plot one circle (the biggest one on bottom-right)
plt.Circle((1, 0), 0.5, 'r')

#plot a set of circles (circles in diagonal)
a=np.arange(11)
out = plt.Circle((a, a), a*0.2, c=a)
plt.colorbar(out)

plt.xlim(0,10)
plt.ylim(0,10)

TypeError: __init__() takes at most 3 arguments (4 given)

In [5]:
a=plt.imread(r'C:\Users\Sean Violante\Documents\Projects\vlfeat\vlfeat\x64\Debug\box.pgm')

In [7]:
a.shape

(224L, 324L)

In [11]:
plt.imshow(a,plt.gray())

In [9]:
%matplotlib qt

In [13]:
with open(r'C:\Users\Sean Violante\Documents\Projects\vlfeat\vlfeat\x64\Debug\dsift.txt','r') as f:
    a_desc=json.load(f)

In [16]:
len(a_desc['Descriptors'])

128