In [7]:
pract_dir=r'C:\Users\Sean Violante\Documents\Projects\practical-instance-recognition-2015a'
f=r'/data/oxbuild_lite/all_souls_000002.jpg'

In [9]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy import ndimage

In [17]:
import cv2

In [10]:
im1=plt.imread(pract_dir+f)

In [26]:
im1a=cv2.cvtColor(im1,cv2.COLOR_RGB2GRAY)

In [22]:
im2=ndimage.rotate(im1a,35)

In [24]:
im3=ndimage.interpolation.zoom(im2,0.7)

In [15]:
%matplotlib qt

In [28]:
plt.subplot(121)
plt.imshow(im1a,plt.gray())
plt.subplot(122)
plt.imshow(im3)


In [6]:
import cyvlfeat.sift.dsift

In [13]:
im3.shape

(859L, 799L, 2L)

In [14]:
im1.shape

(1024L, 677L, 3L)

In [38]:
im1a.shape

(1024L, 677L)

In [15]:
im2.shape


(1227L, 1142L, 3L)

In [23]:
%cd C:\Users\Sean Violante\Documents\Projects\cyvlfeat\build\lib.win-amd64-2.7\cyvlfeat\sift

C:\Users\Sean Violante\Documents\Projects\cyvlfeat\build\lib.win-amd64-2.7\cyvlfeat\sift


In [40]:
x=cyvlfeat.sift.dsift.dsift(im1a,verbose=True)

In [31]:
x

(array([[    4.5,     5.5,     6.5, ...,  1016.5,  1017.5,  1018.5],
        [    4.5,     4.5,     4.5, ...,   671.5,   671.5,   671.5]]),
 array([[  0.,   0.,   0., ...,   3.,   1.,   1.],
        [  0.,   0.,   0., ...,   3.,   1.,   0.],
        [ 27.,  55.,  79., ...,   4.,   4.,   2.],
        ..., 
        [ 42.,  54.,  59., ...,   8.,  27.,  62.],
        [ 13.,  16.,  24., ...,  26.,  21.,  18.],
        [  4.,  10.,  19., ...,   6.,   8.,  13.]], dtype=float32))

In [41]:
im1a.shape

(1024L, 677L)

In [51]:
677 % 12

5

In [58]:
x[0][:,0:10]

array([[  4.5,   5.5,   6.5,   7.5,   8.5,   9.5,  10.5,  11.5,  12.5,
         13.5],
       [  4.5,   4.5,   4.5,   4.5,   4.5,   4.5,   4.5,   4.5,   4.5,
          4.5]])

In [53]:
(1024-5)* (677-6)

683749

In [37]:
x[0][0].shape

(678020L,)

In [42]:
x[1].shape

(128L, 678020L)

In [43]:
1024 //3

341

In [44]:
677//3

225

In [45]:
341*225

76725

step: in bin width
size: bin size
Bounds: [ymin,xmin,ymax,xmax]


In [ ]:
step=1, size=3, bounds=None, window_size=2, norm=False,
          fast=False, float_descriptors=False, geometry=(4, 4, 8),
          verbose=False):